ci: debug end2end tests #7

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,6 +101,9 @@ jobs:
       # Generate job summary
       - name: Generate job summary
         run: cat summary.md >> $GITHUB_STEP_SUMMARY
-      # Print the job outcome (so we can mark it as errored)
-      - name: Print the script outcome
-        run: echo "script outcome ${{steps.e2e_test.outcome}}"
+      # Fail the job if the script step has failed
+      - name: Check for script failure
+        run: |
+          if [[ "${{ steps.failingStep.outcome }}" == "failure" ]]; then
+            exit 1
+          fi
